.PHONY: clean All

All:
	@echo "----------Building project:[ testNewProject - Debug ]----------"
	@cd "testNewProject" && "$(MAKE)" -f  "testNewProject.mk"
clean:
	@echo "----------Cleaning project:[ testNewProject - Debug ]----------"
	@cd "testNewProject" && "$(MAKE)" -f  "testNewProject.mk" clean
