.PHONY: clean All

All:
	@echo "----------Building project:[ s9e79functionTests - Debug ]----------"
	@cd "s9e79functionTests" && "$(MAKE)" -f  "s9e79functionTests.mk"
clean:
	@echo "----------Cleaning project:[ s9e79functionTests - Debug ]----------"
	@cd "s9e79functionTests" && "$(MAKE)" -f  "s9e79functionTests.mk" clean
